# Generated by Django 4.2.6 on 2023-10-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_store_description_alter_store_name_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price_bought',
            new_name='purchase_price',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='price_sold',
            new_name='selling_price',
        ),
    ]
