# Generated by Django 4.2.6 on 2023-10-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_price_bought_item_purchase_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='brand',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
