# Generated by Django 4.2.7 on 2023-11-08 12:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_user_last_accessed_store"),
    ]

    operations = [
        migrations.AddField(
            model_name="store",
            name="is_public",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="store",
            name="description",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
